// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6vb1vJqwZ7C7s4DK_nUdG7jHoO2fHJBc',
    appId: '1:571169544577:web:2c9d3d50f065713acbb080',
    messagingSenderId: '571169544577',
    projectId: 'pettify-96749',
    authDomain: 'pettify-96749.firebaseapp.com',
    storageBucket: 'pettify-96749.appspot.com',
    measurementId: 'G-64EE0CLV17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHuysMGb2tP-O5UAOhK7FB0bWHofN6CZ8',
    appId: '1:571169544577:android:62553e2c9e8897aacbb080',
    messagingSenderId: '571169544577',
    projectId: 'pettify-96749',
    storageBucket: 'pettify-96749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOUnyP03xwdVNzxLkkEkfbBIKBQbs7-A',
    appId: '1:571169544577:ios:46bc62e0d142cd08cbb080',
    messagingSenderId: '571169544577',
    projectId: 'pettify-96749',
    storageBucket: 'pettify-96749.appspot.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZOUnyP03xwdVNzxLkkEkfbBIKBQbs7-A',
    appId: '1:571169544577:ios:46bc62e0d142cd08cbb080',
    messagingSenderId: '571169544577',
    projectId: 'pettify-96749',
    storageBucket: 'pettify-96749.appspot.com',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6vb1vJqwZ7C7s4DK_nUdG7jHoO2fHJBc',
    appId: '1:571169544577:web:a9dcbb5205eecc3bcbb080',
    messagingSenderId: '571169544577',
    projectId: 'pettify-96749',
    authDomain: 'pettify-96749.firebaseapp.com',
    storageBucket: 'pettify-96749.appspot.com',
    measurementId: 'G-H4GF9F37WX',
  );
}
